name: Publish Docker
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: update
    steps:
    - uses: actions/checkout@v2
    - name: Install dependences
      run: |
        sudo apt-get update
        sudo apt-get install git tree -y
    - name: Prepare git
      run: |
        git config --global user.name ${{ secrets.GITHUB_TOKEN }}
        git config --global user.email 'help@castellanidavide.it'
    - name: Update core-createstructure
      run: |
        git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/createstructure/core-createstructure.git
        cd core-createstructure
        git submodule update --init --remote --recursive --merge
        git add *
        git commit -m "Update librerias"
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/createstructure/core-createstructure.git
    - name: Update manager-createstructure
      run: |
        git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/createstructure/manager-createstructure.git
        cd manager-createstructure
        git submodule update --init --remote --recursive --merge
        git add *
        git commit -m "Update librerias"
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/createstructure/manager-createstructure.git
      