name: Publish librerias
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    environment:
      name: check
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libcurl4-openssl-dev libssl-dev -y

    - name: Check files
      run: |
        make all
  update:
    runs-on: ubuntu-latest
    environment:
      name: update
    steps:
    - uses: actions/checkout@v2
    - name: Install dependences
      run: |
        sudo apt-get update
        sudo apt-get install git tree -y
    - name: Prepare git
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email 'help@castellanidavide.it'
    - name: Update core-createstructure
      run: |
        git clone https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/core-createstructure.git
        cd core-createstructure
        git submodule update --init --remote --recursive --merge
        git add *
        git commit -m "Update librerias"
        git push https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/core-createstructure.git
    - name: Update debian-createstructure
      run: |
        git clone https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/debian-createstructure.git
        cd debian-createstructure
        git submodule update --init --remote --recursive --merge
        git add *
        git commit -m "Update librerias"
        git push https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/debian-createstructure.git
    - name: Update manager-createstructure
      run: |
        git clone https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/manager-createstructure.git
        cd manager-createstructure
        git submodule update --init --remote --recursive --merge
        git add *
        git commit -m "Update librerias"
        git push https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/createstructure/manager-createstructure.git
      